services:
  postgres:
    image: postgres:17
    container_name: spring-blog-postgres
    environment:
      POSTGRES_DB: spring_blog
      POSTGRES_USER: spring_blog_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - spring_blog_postgres_data:/var/lib/postgresql/data

volumes:
  spring_blog_postgres_data: